### ISSUE TITLE
Compilation errors when opening the projects

### ISSUE THREAD

**Issue by tonai** [magicleap/MagicLeapUnityExamples#1]
Hello,
I have a lot of compilation errors (about 205) when I just try to open the project with a fresh new install of unity.
Errors look like: 
`Assets\MagicLeap\Examples\Scripts\HandTrackingExample.cs(16,17): error CS0234: The type or namespace name 'Core' does not exist in the namespace 'MagicLeap' (are you missing an assembly reference?)`

How can I fix those errors ?

**Comment by Nihav-Jain** [comment]
Hi @tonai in your git clone, run the following command - `git submodule update --init --remote` and let us know if that fixes the compiler errors.

**Comment by tonai** [comment]
Thank you for your answer, it is indeed much better.
Maybe a little update in the README file would be appreciated.

Also I noticed the following things:
* To be able to use zero integration I needed to `Import Support Libraries` From the `Magic Leap/ML Remote` menu as indicated by the [Using Zero Iteration Unity](https://developer.magicleap.com/en-us/learn/guides/1-3-zero-iteration-unity) guide.
* You need to setup a certificate in the project settings to build your app

I also tried to setup a project manually, following the [Get started in Unity](https://developer.magicleap.com/en-us/learn/guides/unity-setup-intro) guide and I ran into an issue when trying to continue to the [2.0 Control Input - Unity](https://developer.magicleap.com/en-us/learn/guides/unity-user-input-overview) tutorial.

The video is using a controller prefab that is located under a `Assets/MagicLeap` folder, but I don't know where this folder comes from. I don't have it in my newly created project.
I see that this folder exists in this example project.
So should I copy it into my new project ? Or is there a unity asset or something to import ?

Thank you in advance for your answer.

**Comment by MadeinPh1la** [comment]
Please ensure you're updated to the most current versions of our OS and SDK within the Magic Leap Hub, and follow the steps outlined [starting here to install the correct tools](https://developer-docs.magicleap.cloud/docs/guides/unity/getting-started/unity-getting-started). You should be in good shape from there.
